CREATE TABLE auth_group (
    id integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name character varying(150) NOT NULL UNIQUE
);

CREATE TABLE auth_group_permissions (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id),
    FOREIGN KEY (group_id) REFERENCES auth_group(id) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY (permission_id) REFERENCES auth_permission(id) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE auth_permission (
    id integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL,
    CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename)
);

CREATE TABLE django_admin_log (
    id integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL CHECK ((action_flag >= 0)),
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    FOREIGN KEY (content_type_id) REFERENCES django_content_type(id) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY (user_id) REFERENCES users_user(id) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE django_content_type (
    id integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL,
    CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model)
);

CREATE TABLE django_migrations (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);

CREATE TABLE django_session (
    session_key character varying(40) NOT NULL PRIMARY KEY,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);

CREATE TABLE labels_label (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE statuses_status (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL
);

CREATE TABLE tasks_task (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name character varying(150) NOT NULL,
    description text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    author_id bigint,
    executor_id bigint,
    status_id bigint,
    FOREIGN KEY (author_id) REFERENCES users_user(id) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY (executor_id) REFERENCES users_user(id) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY (status_id) REFERENCES statuses_status(id) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE tasks_task_labels (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    task_id bigint NOT NULL,
    label_id bigint NOT NULL,
    CONSTRAINT tasks_task_labels_task_id_label_id_b59bd62c_uniq UNIQUE (task_id, label_id),
    FOREIGN KEY (task_id) REFERENCES tasks_task(id) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY (label_id) REFERENCES labels_label(id) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE users_user (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL UNIQUE,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);

CREATE TABLE users_user_groups (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT users_user_groups_user_id_group_id_b88eab82_uniq UNIQUE (user_id, group_id),
    FOREIGN KEY (user_id) REFERENCES users_user(id) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY (group_id) REFERENCES auth_group(id) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE users_user_user_permissions (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT users_user_user_permissions_user_id_permission_id_43338c45_uniq UNIQUE (user_id, permission_id),
    FOREIGN KEY (user_id) REFERENCES users_user(id) DEFERRABLE INITIALLY DEFERRED,
    FOREIGN KEY (permission_id) REFERENCES auth_permission(id) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX auth_group_name_a6ea08ec_like ON auth_group (name varchar_pattern_ops);
CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON auth_group_permissions (group_id);
CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON auth_group_permissions (permission_id);
CREATE INDEX auth_permission_content_type_id_2f476e4b ON auth_permission (content_type_id);
CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON django_admin_log (content_type_id);
CREATE INDEX django_admin_log_user_id_c564eba6 ON django_admin_log (user_id);
CREATE INDEX django_session_expire_date_a5c62663 ON django_session (expire_date);
CREATE INDEX django_session_session_key_c0390e0f_like ON django_session (session_key varchar_pattern_ops);
CREATE INDEX tasks_task_author_id_33a50930 ON tasks_task (author_id);
CREATE INDEX tasks_task_executor_id_1fab67ee ON tasks_task (executor_id);
CREATE INDEX tasks_task_labels_label_id_fdb0c9e0 ON tasks_task_labels (label_id);
CREATE INDEX tasks_task_labels_task_id_78ec38df ON tasks_task_labels (task_id);
CREATE INDEX tasks_task_status_id_899d2b90 ON tasks_task (status_id);
CREATE INDEX users_user_groups_group_id_9afc8d0e ON users_user_groups (group_id);
CREATE INDEX users_user_groups_user_id_5f6f5a90 ON users_user_groups (user_id);
CREATE INDEX users_user_user_permissions_permission_id_0b93982e ON users_user_user_permissions (permission_id);
CREATE INDEX users_user_user_permissions_user_id_20aca447 ON users_user_user_permissions (user_id);
CREATE INDEX users_user_username_06e46fe6_like ON users_user (username varchar_pattern_ops);