# Generated by Django 4.2.21 on 2025-05-10 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_label_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned_to',
            new_name='assignee',
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='Unnamed Task', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Task_labels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.label')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_manager.task')),
            ],
            options={
                'db_table': 'task_manager_task_labels',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, through='task_manager.Task_labels', to='task_manager.label'),
        ),
    ]
