- name: Test & publish code coverage
  uses: paambaati/codeclimate-action@v5.0.0
  with:
    coverageCommand: make test-coverage
    debug: true

- name: Upload coverage to Code Climate
  run: ./cc-reporter after-build --exit-code $?
  env:
    CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
